apiVersion: v1
kind: PersistentVolume
metadata:
  name: webproje-pv
  namespace: odeon
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webproje-pv-claim
  namespace: odeon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi