apiVersion: v1
kind: Service
metadata:
  name: webproje-service
  namespace: odeon
  labels:
    app: webproje
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30800
  selector:
    app: webproje