apiVersion: apps/v1
kind: Deployment
metadata:
  name: webproje-deployment
  labels:
    app: webproje
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webproje
  template:
    metadata:
      labels:
        app: webproje
    spec:
      containers:
      - name: webproje
        image: ayseyavass/webproje:latest
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_DB
          value: VTKitapSatis
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret 
              key: password
        - name: POSTGRES_HOST
          value: postgres-service 
        - name: POSTGRES_PORT
          value: "5432" 
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: webproje-volume
          mountPath: /app/data
      volumes:
      - name: webproje-volume
        persistentVolumeClaim:
          claimName: webproje-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: webproje-service
  labels:
    app: webproje
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webproje