apiVersion: apps/v1
kind: Deployment
metadata:
  name: webProje-deployment
  labels:
    app: webProje
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: webProje
  template:
    metadata:
      labels:
        app: webProje
    spec:
      containers:
      - name: webProje
        image: webProje/webProje:latest 
        ports:
        - containerPort: 80 
        env:
        - name: postgresqlDatabase
          value: VTKitapSatis
        - name: postgresqlUsername
          value: postgres
        - name: postgresqlPassword
          valueFrom:
            secretKeyRef:
              name: Password  
              key: 1234
        - name: Host
          value: localhost 
        - name: Port
          value: 5432
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: webProje-volume
          mountPath: /app/data

      volumes:
      - name: webProje-volume
        persistentVolumeClaim:
          claimName: webProje-pv-claim  
---
apiVersion: v1
kind: Service
metadata:
  name: webProje-service
  labels:
    app: webProje
spec:
  type: LoadBalancer
  ports:
  - port: 80  # External Port
    targetPort: 80  # Internal Port in the Pod
  selector:
    app: webProje


nodeSelector:
  cloud.google.com/gke-nodepool: default-pool

tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"

persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 1Gi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: webproje.example.com
      paths:
        - /
